#! /bin/bash

# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export PROJECT_ID='[PROJECT_ID]'
export REGISTRY_ID='[CLOUD_IOT_CORE_REGISTRY_ID]'
export DEVICE_ID='[CLOUD_IOT_CORE_DEVICE_ID]'
export PRIVATE_KEY_FILE='[PATH_TO_DEVICE_PRIVATE_KEY]'
export CLOUD_REGION='[REGION_NAME]'
export CA_CERTS='[PATH_TO_GOOGLE_ROOT_CERT]'
export ALGORITHM='[KEY_PAIR_ALGO, RS256 or ES256]'
export PAYLOAD_SIZE=[NUMBER_OF_FIELDS_IN_PAYLOAD]

